//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetriCam2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetriCamLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetriCamLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetriCam2.MetriCamLocale", typeof(MetriCamLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera is not connected..
        /// </summary>
        internal static string error_cameraNotConnected {
            get {
                return ResourceManager.GetString("error_cameraNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot be released..
        /// </summary>
        internal static string error_cannotReleaseInterface {
            get {
                return ResourceManager.GetString("error_cannotReleaseInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be changed while the camera is connected..
        /// </summary>
        internal static string error_changeParameterConnected {
            get {
                return ResourceManager.GetString("error_changeParameterConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to camera failed..
        /// </summary>
        internal static string error_connectionFailed {
            get {
                return ResourceManager.GetString("error_connectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to camera with IP address {0}..
        /// </summary>
        internal static string error_connectionToManualIpFailed {
            get {
                return ResourceManager.GetString("error_connectionToManualIpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate transformation failed..
        /// </summary>
        internal static string error_coordinateTransformationFailed {
            get {
                return ResourceManager.GetString("error_coordinateTransformationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting from camera failed..
        /// </summary>
        internal static string error_disconnectionFailed {
            get {
                return ResourceManager.GetString("error_disconnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get 3D coordinates..
        /// </summary>
        internal static string error_get3DCoordinates {
            get {
                return ResourceManager.GetString("error_get3DCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude image not supported..
        /// </summary>
        internal static string error_getAmplitudeImage {
            get {
                return ResourceManager.GetString("error_getAmplitudeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No confidence map available..
        /// </summary>
        internal static string error_getConfidenceMap {
            get {
                return ResourceManager.GetString("error_getConfidenceMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve data..
        /// </summary>
        internal static string error_getData {
            get {
                return ResourceManager.GetString("error_getData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve data description..
        /// </summary>
        internal static string error_getDataDescription {
            get {
                return ResourceManager.GetString("error_getDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve distance data..
        /// </summary>
        internal static string error_getDistances {
            get {
                return ResourceManager.GetString("error_getDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve flags..
        /// </summary>
        internal static string error_getFlags {
            get {
                return ResourceManager.GetString("error_getFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get integration time..
        /// </summary>
        internal static string error_getIntegrationTime {
            get {
                return ResourceManager.GetString("error_getIntegrationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve intensity data..
        /// </summary>
        internal static string error_getIntensities {
            get {
                return ResourceManager.GetString("error_getIntensities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get modulation frequency..
        /// </summary>
        internal static string error_getModulationFrequency {
            get {
                return ResourceManager.GetString("error_getModulationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get current value of paramter &quot;{0}&quot;..
        /// </summary>
        internal static string error_getParameter {
            get {
                return ResourceManager.GetString("error_getParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine valid parameter values for &quot;{0}&quot;..
        /// </summary>
        internal static string error_getParameterValues {
            get {
                return ResourceManager.GetString("error_getParameterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera has to be connected to determine the serial number..
        /// </summary>
        internal static string error_getSerial {
            get {
                return ResourceManager.GetString("error_getSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get serial number..
        /// </summary>
        internal static string error_getSerialNumber {
            get {
                return ResourceManager.GetString("error_getSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera type does not support exposure mode settings..
        /// </summary>
        internal static string error_getSetExposureMode {
            get {
                return ResourceManager.GetString("error_getSetExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration time settings not supported for this camera type..
        /// </summary>
        internal static string error_getSetIntegrationTime {
            get {
                return ResourceManager.GetString("error_getSetIntegrationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulation frequency settings not supported for this camera type..
        /// </summary>
        internal static string error_getSetModulationFrequency {
            get {
                return ResourceManager.GetString("error_getSetModulationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera type does not support trigger mode settings..
        /// </summary>
        internal static string error_getSetTriggerMode {
            get {
                return ResourceManager.GetString("error_getSetTriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel with the name &apos;{0}&apos; is not active..
        /// </summary>
        internal static string error_inactiveChannelName {
            get {
                return ResourceManager.GetString("error_inactiveChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera SDK initialization failed..
        /// </summary>
        internal static string error_initSDK {
            get {
                return ResourceManager.GetString("error_initSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Channels combination: {0}..
        /// </summary>
        internal static string error_invalidChannelCombination {
            get {
                return ResourceManager.GetString("error_invalidChannelCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel by the name &apos;{0}&apos; supported..
        /// </summary>
        internal static string error_invalidChannelName {
            get {
                return ResourceManager.GetString("error_invalidChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel &apos;{0}&apos; is not active, or unsupported by the camera..
        /// </summary>
        internal static string error_invalidChannelNumber {
            get {
                return ResourceManager.GetString("error_invalidChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid modulation frequency adjusted..
        /// </summary>
        internal static string error_invalidModulationFrequency {
            get {
                return ResourceManager.GetString("error_invalidModulationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string error_invalidParameterValue {
            get {
                return ResourceManager.GetString("error_invalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa SDK: Coordinate transform float failed..
        /// </summary>
        internal static string error_mesaSDKCorrdinateTransformFailed {
            get {
                return ResourceManager.GetString("error_mesaSDKCorrdinateTransformFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not allocate memory for bitmap buffer..
        /// </summary>
        internal static string error_outOfMemoryBitmapBuffer {
            get {
                return ResourceManager.GetString("error_outOfMemoryBitmapBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available webcams are currently in use or newly connected webcams have not been recognized..
        /// </summary>
        internal static string error_outOfWebcams {
            get {
                return ResourceManager.GetString("error_outOfWebcams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value is invalid..
        /// </summary>
        internal static string error_parameterValueInvalid {
            get {
                return ResourceManager.GetString("error_parameterValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string has a wrong format..
        /// </summary>
        internal static string error_parseString {
            get {
                return ResourceManager.GetString("error_parseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not supported by the camera..
        /// </summary>
        internal static string error_propertyNotSupported {
            get {
                return ResourceManager.GetString("error_propertyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key not found! Please reinstall..
        /// </summary>
        internal static string error_registry {
            get {
                return ResourceManager.GetString("error_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the registry key was not found, or the path set in the registry is not valid! Please ensure, that your ppp and pap files of your PMD camera and the pmdaccess2.dll file are present in the execution directory of this application or in the MetriCam SDK folder..
        /// </summary>
        internal static string error_registryPathInvalid {
            get {
                return ResourceManager.GetString("error_registryPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set exposure mode..
        /// </summary>
        internal static string error_setExposureMode {
            get {
                return ResourceManager.GetString("error_setExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set integration time..
        /// </summary>
        internal static string error_setIntegrationTime {
            get {
                return ResourceManager.GetString("error_setIntegrationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP may not be set for a connected camera..
        /// </summary>
        internal static string error_setIP {
            get {
                return ResourceManager.GetString("error_setIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set modulation frequency..
        /// </summary>
        internal static string error_setModulationFrequency {
            get {
                return ResourceManager.GetString("error_setModulationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set parameter &quot;{0}&quot; to value &quot;{1}&quot;..
        /// </summary>
        internal static string error_setParameter {
            get {
                return ResourceManager.GetString("error_setParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set resolution..
        /// </summary>
        internal static string error_setResolution {
            get {
                return ResourceManager.GetString("error_setResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set ROI..
        /// </summary>
        internal static string error_setROI {
            get {
                return ResourceManager.GetString("error_setROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number may not be set for a connected camera..
        /// </summary>
        internal static string error_setSerial {
            get {
                return ResourceManager.GetString("error_setSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stride does not match..
        /// </summary>
        internal static string error_strideMatch {
            get {
                return ResourceManager.GetString("error_strideMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensor type &apos;{0}&apos; is not supported by the camera..
        /// </summary>
        internal static string error_unsupportedSensorType {
            get {
                return ResourceManager.GetString("error_unsupportedSensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed..
        /// </summary>
        internal static string error_updateFailed {
            get {
                return ResourceManager.GetString("error_updateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong device..
        /// </summary>
        internal static string error_wrongDevice {
            get {
                return ResourceManager.GetString("error_wrongDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error ocurred..
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
